# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import coordinator_pb2 as coordinator__pb2

class CoordinatorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.init = channel.unary_unary(
                '/coordinator.CoordinatorService/init',
                request_serializer=coordinator__pb2.PeerAnnounceRequest.SerializeToString,
                response_deserializer=coordinator__pb2.PeerAnnounceReply.FromString)
        self.ping = channel.unary_unary(
                '/coordinator.CoordinatorService/ping',
                request_serializer=coordinator__pb2.Ping.SerializeToString,
                response_deserializer=coordinator__pb2.Pong.FromString)
        self.getRoutingInfo = channel.unary_stream(
                '/coordinator.CoordinatorService/getRoutingInfo',
                request_serializer=coordinator__pb2.PeerRoutingRequest.SerializeToString,
                response_deserializer=coordinator__pb2.PeerRouting.FromString)
        self.removeRoutingInfo = channel.unary_unary(
                '/coordinator.CoordinatorService/removeRoutingInfo',
                request_serializer=coordinator__pb2.PeerRoutingRequest.SerializeToString,
                response_deserializer=coordinator__pb2.Void.FromString)
        self.sendRoutingInfo = channel.unary_unary(
                '/coordinator.CoordinatorService/sendRoutingInfo',
                request_serializer=coordinator__pb2.RoutingInfoData.SerializeToString,
                response_deserializer=coordinator__pb2.Void.FromString)
        self.readyForDataMigration = channel.unary_unary(
                '/coordinator.CoordinatorService/readyForDataMigration',
                request_serializer=coordinator__pb2.PeerAnnounceRequest.SerializeToString,
                response_deserializer=coordinator__pb2.Void.FromString)
        self.provideGlobalRoutingInfo = channel.unary_stream(
                '/coordinator.CoordinatorService/provideGlobalRoutingInfo',
                request_serializer=coordinator__pb2.Void.SerializeToString,
                response_deserializer=coordinator__pb2.RoutingInfoData.FromString)


class CoordinatorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def init(self, request, context):
        """init message sent node to neighbours to coordinator  interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getRoutingInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeRoutingInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendRoutingInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readyForDataMigration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def provideGlobalRoutingInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'init': grpc.unary_unary_rpc_method_handler(
                    servicer.init,
                    request_deserializer=coordinator__pb2.PeerAnnounceRequest.FromString,
                    response_serializer=coordinator__pb2.PeerAnnounceReply.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=coordinator__pb2.Ping.FromString,
                    response_serializer=coordinator__pb2.Pong.SerializeToString,
            ),
            'getRoutingInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.getRoutingInfo,
                    request_deserializer=coordinator__pb2.PeerRoutingRequest.FromString,
                    response_serializer=coordinator__pb2.PeerRouting.SerializeToString,
            ),
            'removeRoutingInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.removeRoutingInfo,
                    request_deserializer=coordinator__pb2.PeerRoutingRequest.FromString,
                    response_serializer=coordinator__pb2.Void.SerializeToString,
            ),
            'sendRoutingInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.sendRoutingInfo,
                    request_deserializer=coordinator__pb2.RoutingInfoData.FromString,
                    response_serializer=coordinator__pb2.Void.SerializeToString,
            ),
            'readyForDataMigration': grpc.unary_unary_rpc_method_handler(
                    servicer.readyForDataMigration,
                    request_deserializer=coordinator__pb2.PeerAnnounceRequest.FromString,
                    response_serializer=coordinator__pb2.Void.SerializeToString,
            ),
            'provideGlobalRoutingInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.provideGlobalRoutingInfo,
                    request_deserializer=coordinator__pb2.Void.FromString,
                    response_serializer=coordinator__pb2.RoutingInfoData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coordinator.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    if hasattr(server, "add_registered_method_handlers"):
        server.add_registered_method_handlers('coordinator.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.CoordinatorService/init',
            coordinator__pb2.PeerAnnounceRequest.SerializeToString,
            coordinator__pb2.PeerAnnounceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.CoordinatorService/ping',
            coordinator__pb2.Ping.SerializeToString,
            coordinator__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def getRoutingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/coordinator.CoordinatorService/getRoutingInfo',
            coordinator__pb2.PeerRoutingRequest.SerializeToString,
            coordinator__pb2.PeerRouting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def removeRoutingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.CoordinatorService/removeRoutingInfo',
            coordinator__pb2.PeerRoutingRequest.SerializeToString,
            coordinator__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def sendRoutingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.CoordinatorService/sendRoutingInfo',
            coordinator__pb2.RoutingInfoData.SerializeToString,
            coordinator__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def readyForDataMigration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.CoordinatorService/readyForDataMigration',
            coordinator__pb2.PeerAnnounceRequest.SerializeToString,
            coordinator__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def provideGlobalRoutingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/coordinator.CoordinatorService/provideGlobalRoutingInfo',
            coordinator__pb2.Void.SerializeToString,
            coordinator__pb2.RoutingInfoData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
